### ISSUE TITLE
possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit.

### ISSUE THREAD

**Issue by bernex** [molnarg/node-http2#206]
Hi, how I can fix it?

`
(node) warning: possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:665:33)
    at first (c:\Folders\Sand\koa2-kickstarter\node_modules\ee-first\index.js:43:10)
    at onSocket (c:\Folders\Sand\koa2-kickstarter\node_modules\on-finished\index.js:114:16)
    at attachFinishedListener (c:\Folders\Sand\koa2-kickstarter\node_modules\on-finished\index.js:119:5)
    at attachListener (c:\Folders\Sand\koa2-kickstarter\node_modules\on-finished\index.js:146:5)
    at onFinished (c:\Folders\Sand\koa2-kickstarter\node_modules\on-finished\index.js:52:3)
    at Server.<anonymous> (c:\Folders\Sand\koa2-kickstarter\node_modules\koa\lib\application.js:134:7)
    at emitTwo (events.js:87:13)
    at Server.emit (events.js:172:7)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:665:33)
    at first (c:\Folders\Sand\koa2-kickstarter\node_modules\ee-first\index.js:43:10)
    at onSocket (c:\Folders\Sand\koa2-kickstarter\node_modules\on-finished\index.js:114:16)
    at attachFinishedListener (c:\Folders\Sand\koa2-kickstarter\node_modules\on-finished\index.js:119:5)
    at attachListener (c:\Folders\Sand\koa2-kickstarter\node_modules\on-finished\index.js:146:5)
    at onFinished (c:\Folders\Sand\koa2-kickstarter\node_modules\on-finished\index.js:52:3)
    at Server.<anonymous> (c:\Folders\Sand\koa2-kickstarter\node_modules\koa\lib\application.js:134:7)
    at emitTwo (events.js:87:13)
    at Server.emit (events.js:172:7)
`

**Comment by akc42** [comment]
I get this too.  I though at first it was related to using push, where I sent a lot of files one after the other (about 40) but it has nothing to do with it, as it still occurs soon after I start my application up.

I have no idea if this is a slow leak or just going over the limit slightly, as the warning is only produced once of each event and then is never repeated.

**Comment by akc42** [comment]
I discovered what this was and its NOT a memory leak.  Its the way serve-static handles streams.  I've actually just raised this as an issue against that repository
https://github.com/expressjs/serve-static/issues/87
