### ISSUE TITLE
flow.js:170 assertion failure

### ISSUE THREAD

**Issue by bjb568** [molnarg/node-http2#217]
This happens in 3.3.5 instead of #207:

```
assert.js:90
  throw new assert.AssertionError({
  ^
AssertionError: false == true
    at Flow._read (…/node_modules/http2/lib/protocol/flow.js:170:5)
    at Flow.Readable.read (_stream_readable.js:355:10)
    at Flow.read (…/node_modules/http2/lib/protocol/flow.js:194:34)
    at maybeReadMore_ (_stream_readable.js:461:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

This happens on multiple node versions I've tried, including 6.2.1 and 6.5.0.

**Comment by James-1064** [comment]
I'm also having the same issue:
The server starts up and everything is fine, but as soon as i browse to https://localboom:50100 the initial page loads and the server crashes with the following...

Any help much appreciated !

```
$ gulp host-dev 
[15:05:38] Using gulpfile C:\Dev\cxBoom\Source\Boombastic\boombastic\gulpfile.js 
[15:05:38] Starting 'host-dev'...  
[15:05:38] Finished 'host-dev' after 33 ms
[15:05:38] Dev Boombastic started https://localboom:50100
[15:05:38] LiveReload started on port 35729
(node:3272) Warning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit     
(node:3272) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
 
assert.js:85
  throw new assert.AssertionError({

AssertionError: false == true
    at Flow._read (C:\Dev\cxBoom\Source\Boombastic\boombastic\node_modules\http2\lib\protocol\flow.js:170:5)
    at Flow.Readable.read (_stream_readable.js:348:10)
    at Flow.read (C:\Dev\cxBoom\Source\Boombastic\boombastic\node_modules\http2\lib\protocol\flow.js:194:34)
    at maybeReadMore_ (_stream_readable.js:455:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```  
This is being called from the following gulp snippet:

```
gulp.task('host-dev', function() {
	connect.server({
		name: 		'Dev Boombastic',
		https: 
		{
			key: 		fs.readFileSync('../../../Certs/localboom.key', 'utf8'),
			cert: 		fs.readFileSync('../../../Certs/localboom.crt', 'utf8')
		},
		port: 		pkg.app.devURL.port,
		host: 		pkg.app.devURL.host, 
		root: 		pkg.paths.distDev,
		livereload: true
	});
});
```
