### ISSUE TITLE
error event FRAME_SIZE_ERROR

### ISSUE THREAD

**Issue by clarencetw** [molnarg/node-http2#218]
when I send the request to apple I will get the 
events.js:165
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (FRAME_SIZE_ERROR)
    at Endpoint.emit (events.js:163:17)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback](timers.js:529:5)

so who to catch this error

**Comment by sumeet559** [comment]
I got the same too.
Error: Uncaught, unspecified "error" event. (FRAME_SIZE_ERROR)
    at Endpoint.emit (events.js:163:17)
   at runCallback (timers.js:570:20)
   at tryOnImmediate (timers.js:550:5)
 at processImmediate [as _immediateCallback] (timers.js:529:5)

**Comment by maksymseleznov** [comment]
+1, how to fix it?

**Comment by abhijeet-sonawane** [comment]
I got the same error too.

**Comment by jdelgadoalfonso** [comment]
+1, same error
