### ISSUE TITLE
Error: stream.push() after EOF

### ISSUE THREAD

**Issue by indieyourself** [molnarg/node-http2#243]
stream.push() after EOF Error: stream.push() after EOF
    at readableAddChunk (_stream_readable.js:133:17)
    at Connection.Readable.push (_stream_readable.js:111:10)
    at Connection._parentPush (/home/susan/jsworkspace/serverTrunk/game-server/node_modules/http2/lib/protocol/flow.js:243:32)
    at Connection._push (/home/susan/jsworkspace/serverTrunk/game-server/node_modules/http2/lib/protocol/flow.js:255:17)
    at Connection.push (/home/susan/jsworkspace/serverTrunk/game-server/node_modules/http2/lib/protocol/flow.js:286:23)
    at Connection._restoreWindow (/home/susan/jsworkspace/serverTrunk/game-server/node_modules/http2/lib/protocol/flow.js:115:10)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by adeelzx** [comment]
Hey
Did you get the resolution of this error ?
