### ISSUE TITLE
throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by mrG0bliN** [molnarg/node-http2#252]
node 9.3.0
win 10 x64

Console log 
`[06:14:34] Did you forget to signal async completion?                          
events.js:136                                                                  
      throw er; // Unhandled 'error' event                                     
      ^                                                                        
                                                                               
Error: Sending illegal frame (DATA) in CLOSED state.                           
    at Stream.transition [as _transition] (D:\LAN\WORK\7777Taxi\7777taxi.com\no
de_modules\http2\lib\protocol\stream.js:628:33)                                
    at Stream._pushUpstream (D:\LAN\WORK\7777Taxi\7777taxi.com\node_modules\htt
p2\lib\protocol\stream.js:230:8)                                               
    at Stream._write (D:\LAN\WORK\7777Taxi\7777taxi.com\node_modules\http2\lib\
protocol\stream.js:307:25)                                                     
    at doWrite (_stream_writable.js:399:12)                                    
    at writeOrBuffer (_stream_writable.js:385:5)                               
    at Stream.Writable.write (_stream_writable.js:292:11)                      
    at OutgoingResponse._write (D:\LAN\WORK\7777Taxi\7777taxi.com\node_modules\
http2\lib\http.js:336:17)                                                      
    at doWrite (_stream_writable.js:399:12)                                    
    at writeOrBuffer (_stream_writable.js:385:5)                               
    at OutgoingResponse.Writable.write (_stream_writable.js:292:11)            
error Command failed with exit code 1.                                         
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this com
mand. `

i catch this bug after 5-10 repeat pushing button 'reload page' in chrome canary x64

**Comment by mrG0bliN** [comment]
hello?

**Comment by mrG0bliN** [comment]
close
