### ISSUE TITLE
Error: Sending illegal frame (HEADERS) in CLOSED state.

### ISSUE THREAD

**Issue by mrG0bliN** [molnarg/node-http2#254]
```
[Browsersync] Serving files from: public
[16:12:30] 'server:setting' errored after 25 s
[16:12:30] Error: Sending illegal frame (HEADERS) in CLOSED state.
    at Stream.transition [as _transition] (D:\FRONTEND\www\company-m4leads-com\node_modules\http2\lib\protocol\stream.js:628:33)
    at Stream._pushUpstream (D:\FRONTEND\www\company-m4leads-com\node_modules\http2\lib\protocol\stream.js:230:8)
    at Stream.headers (D:\FRONTEND\www\company-m4leads-com\node_modules\http2\lib\protocol\stream.js:101:8)
    at OutgoingResponse.writeHead (D:\FRONTEND\www\company-m4leads-com\node_modules\http2\lib\http.js:731:15)
    at OutgoingResponse._implicitHeaders (D:\FRONTEND\www\company-m4leads-com\node_modules\http2\lib\http.js:737:10)
    at OutgoingResponse.write (D:\FRONTEND\www\company-m4leads-com\node_modules\http2\lib\http.js:746:8)
    at ReadStream.ondata (_stream_readable.js:666:20)
    at ReadStream.emit (events.js:182:13)
    at ReadStream.EventEmitter.emit (domain.js:460:23)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at ReadStream.Readable.push (_stream_readable.js:219:10)
    at lazyFs.read (internal/fs/streams.js:181:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:460:17)
[16:12:30] 'default' errored after 29 s
[16:12:30] The following tasks did not complete: watchme
[16:12:30] Did you forget to signal async completion?
error Command failed with exit code 1.
```
Hello, i repeat F5 so fast and found this bug D: 
stream crash after this !

**Comment by mrG0bliN** [comment]
dead issues
