### ISSUE TITLE
example with HTTP2_PLAIN doesn't work

### ISSUE THREAD

**Issue by kesla** [molnarg/node-http2#87]
I get this error:

```
    throw new Error('options.pfx or options.key and options.cert are required!
          ^
Error: options.pfx or options.key and options.cert are required!
    at Object.createServerTLS [as createServer] (/Users/davidbjorklund/projects/foo/node_modules/http2/lib/http.js:564:11)
    at Object.<anonymous> (/Users/davidbjorklund/projects/foo/node_modules/http2/example/server.js:20:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

is `{ plain: true }` not supported?

**Comment by TedMN** [comment]
The example is fixed but the documentation around server still exists.  It is unclear that your default server is TLS unless you look at the exports and see it mapped to TLS.  The confusion is further compounded by the documentation in the same file http.js.  It says you can pass either.  Which is true for the function, but not for what is exported.   These comments are called the public API but this really is not true or is out of date.

**Comment by gajus** [comment]
@molnarg The documentation needs updating. `{plain: true}` (as other have pointed out) does not work. To start a server that accepts connections over TCP user needs to use `http2.raw.createServer(handler)`.
